
services:
  blue:
    build: .
    container_name: blue
    expose:
      - "5000"
    environment:
      - COLOR=BLUE
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 3s
      retries: 3

  green:
    build: .
    container_name: green
    expose:
      - "5000"
    environment:
      - COLOR=GREEN
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 3s
      retries: 3

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx
    depends_on:
      - blue
      - green
