http{
	#include /etc/nginx/upstream.conf;

	upstream app{
		server blue:5000 weight=3;
		server green:5000 weight=1;
	}

	server{
		listen 80;
		location / {
			proxy_pass http://app;
		}
	}
}

events{

}
